name: rowlbertosmedia
favicon: null
layout_spectrum: 0.9600491165183485
typography_spectrum: 0.8336101942695677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.693561126710847
  lightness: 0.6129973141942173
  saturation: 0.3840079642832279
  rhythmicContrast: 0.051995019195601344
purpose: []
