name: rowlbertosmedia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d4c83'
    - '#c1bfb2'
    - '#b4785e'
    - '#9a1d21'
    - '#00e0f9'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
